version: '3.6'
volumes:
  exec_data:
services:
  bloqCat-api:
    image: leqo/bloqcat-api:latest
    ports:
      - "5000:5000"
    networks:
      - default

  ##### Winery ###
  winery:
    image: leqo/winery:latest
    environment:
      WINERY_HOSTNAME: ${PUBLIC_HOSTNAME}
      WORKFLOWMODELER_HOSTNAME: ${PUBLIC_HOSTNAME}
      TOPOLOGYMODELER_HOSTNAME: ${PUBLIC_HOSTNAME}
      CONTAINER_HOSTNAME: ${PUBLIC_HOSTNAME}
      WINERY_REPOSITORY_URL: https://github.com/leqo/bloqcat-modeling
    ports:
      - "8080:8080"
    networks:
      - default

  db:
    build:
      context: ./db
    image: leqo/bloqcat-db:latest
    environment:
      POSTGRES_USERS: 'planqk:planqk|patternatlas:patternatlas'
      POSTGRES_DATABASES: 'planqk:planqk|patternatlas:patternatlas'
      ATLAS_DB: planqk
      PATTERNATLAS_DB: patternatlas
    ports:
      - "5060:5060"
    networks:
      - default

  qc-atlas-ui:
    image: leqo/qc-atlas-ui:latest
    depends_on:
      - config-server
    environment:
      QC_ATLAS_HOST_NAME: localhost
      QC_ATLAS_PORT: 6626
      PATTERN_ATLAS_HOST_NAME: localhost
      PATTERN_ATLAS_PORT: 1977
      PATTERN_ATLAS_UI_HOST_NAME: localhost
      PATTERN_ATLAS_UI_PORT: 1978
      NISQ_ANALYZER_HOST_NAME: localhost
      NISQ_ANALYZER_PORT: 5010
      QPROV_HOST_NAME: localhost
      QPROV_PORT: 5020
      LATEX_RENDERER_HOST_NAME: localhost
      LATEX_RENDERER_PORT: 5030
    ports:
      - "80:80"
    volumes:
      - ./config:/opt/init-config.d
    networks:
      - default

  qc-atlas-api:
    image: leqo/qc-atlas-api:latest
    volumes:
      - /home/leqo/Documents/github/qc-atlas-content/concrete_solutions:/opt/tomcat/temp/qc-atlas
    environment:
      POSTGRES_HOSTNAME: db
      POSTGRES_PORT: 5060
      POSTGRES_USER: planqk
      POSTGRES_PASSWORD: planqk
      POSTGRES_DB: planqk
    ports:
      - "6626:6626"
    networks:
      - default

  pattern-atlas-api:
    image: leqo/pattern-atlas-api:latest
    environment:
      JDBC_DATABASE_URL: db
      JDBC_DATABASE_USERNAME: patternatlas
      JDBC_DATABASE_PASSWORD: patternatlas
      JDBC_DATABASE_PORT: 5060
      DB_INIT_USER: patternatlas
      DB_INIT_PASSWORD: patternatlas
      LATEX_RENDERER_HOST_NAME: latex-renderer
      LATEX_RENDERER_PORT: 5030
      JDBC_DATABASE_NAME: patternatlas
      PATTERN_ATLAS_FETCH_INITIAL_DATA: 'true'
      HAL_EXPLORER: 'false'
      SPRING_PROFILES_ACTIVE: docker
      JWK_URI: http://auth:8080/realms/patternatlas/protocol/openid-connect/certs
      SECURITY_LOGLEVEL: info
    ports:
      - "1977:1977"
    networks:
      - default
    depends_on:
      - db
      - latex-renderer

  pattern-atlas-ui:
    image: leqo/pattern-atlas-ui:latest
    depends_on:
      - config-server
    environment:
      PATTERN_ATLAS_API_HOST_NAME: localhost
      PATTERN_ATLAS_API_PORT: 1977
      LATEX_RENDERER_HOST_NAME: localhost
      LATEX_RENDERER_PORT: 5030
      URL_SCHEME: http
      AUTH_REALM_URL: http://localhost:7080/realms/patternatlas
    ports:
      - "1978:80"
    networks:
      - default

  auth:
    image: quay.io/keycloak/keycloak:18.0.0
    command: start-dev --import-realm
    volumes:
      - ./keycloak_import:/opt/keycloak/data/import
    environment:
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_ADMIN: admin
    ports:
      - "7080:8080"
    networks:
      - default

  latex-renderer:
    image: leqo/latex-renderer:latest
    ports:
      - "5030:5030"

  config-server:
    image: quay.io/coreos/etcd:latest
    environment:
      ETCD_NAME: config-node1
      ETCD_CORS: "*"
      ETCD_ADVERTISE_CLIENT_URLS: "http://config-server:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCDCTL_API: 3
    ports:
      - "2379:2379"
    networks:
      - default

networks:
  default:
    driver: bridge
